const organizer_team_data = [
    {
        id : 1,
        Person_name : 'Patricia Knott', 
        Person_role : 'Web Developer' ,
        Person_IMG : "https://image.ibb.co/c9rY6J/profile02.jpg" ,
        Link_FB : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_instagram : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_twitter : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_linkedin : "https://www.youtube.com/?gl=IN&tab=r1", 
    },
    {
        id : 2,
        Person_name : 'Patricia Knott', 
        Person_role : 'Web Developer' ,
        Person_IMG : "https://picsum.photos/250/350?image=1027" ,
        Link_FB : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_instagram : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_twitter : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_linkedin : "https://www.youtube.com/?gl=IN&tab=r1", 
    },
    {
        id : 3,
        Person_name : 'Patricia Knott', 
        Person_role : 'Web Developer' ,
        Person_IMG : "https://picsum.photos/250/350?image=839" ,
        Link_FB : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_instagram : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_twitter : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_linkedin : "https://www.youtube.com/?gl=IN&tab=r1", 
    },
    {
        id : 4,
        Person_name : 'Patricia Knott', 
        Person_role : 'Web Developer' ,
        Person_IMG : "https://picsum.photos/250/350?image=857" ,
        Link_FB : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_instagram : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_twitter : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_linkedin : "https://www.youtube.com/?gl=IN&tab=r1", 
    },
    {
        id : 5,
        Person_name : 'Patricia Knott', 
        Person_role : 'Web Developer' ,
        Person_IMG : "https://picsum.photos/250/350?image=836" ,
        Link_FB : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_instagram : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_twitter : "https://www.youtube.com/?gl=IN&tab=r1",
        Link_linkedin : "https://www.youtube.com/?gl=IN&tab=r1", 
    },
]

export default organizer_team_data;